audit_header: false
title: Albany, OR Real Estate Video Blog with Jason Cadwell
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

emma:
  lightbox:
  form:

client:
  name: Jason Cadwell
  title:
  license_number:
  about_markdown: |
    Jason was born in Corvallis grew up in Sweet Home, and graduated from Sweet Home High School.  After attending Linn Benton Community College and Oregon State University, he worked for Hewlett Packard.  Jason found real estate to be his passion and was licensed in 2001.  He worked for The Prudential Real Estate Professionals, then Re/Max Integrity, and in June of 2013 he started his own company - Cadwell Realty Group. 
  market: Albany, OR
  brand: Cadwell Realty Group
  brokerage: 
  address: 226 NW Hickory St<br>Albany, OR 97321
  phone: 541-619-4303
  phone_type:
  phone2:
  phone2_type:
  email: Jason@CadwellRealtyGroup.com
  url: http://www.ValleyOregonHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.valleyoregonhomes.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.valleyoregonhomes.com/search/advanced_search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.valleyoregonhomes.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.valleyoregonhomes.com/search/advanced_search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/JasonCadwellRealtyGroup
  linkedin_url: https://www.zillow.com/profile/jason366/
  gplus_url:
  youtube_url: https://www.youtube.com/c/JasonCadwellCRG
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/jason366/
  trulia_url:
  yelp_url: https://www.yelp.com/biz/cadwell-realty-group-albany-2
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#e12024'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgb(238, 238, 238)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
